// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_joystickbuttons.cpp"
#include "EWIEGA46WW/moc_navbar.cpp"
#include "EWIEGA46WW/moc_streamingvideo.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
